export const CHANGE_ACTUAL_CITY = `CHANGE_ACTUAL_CITY`;
export const GET_CITY_OFFERS = `GET_CITY_OFFERS`;
export const ADD_REVIEWS = `ADD_REVIEWS`;
export const ADD_NEIGHBOUR_PLACES = `ADD_NEIGHBOUR_PLACES`;
export const CHANGE_ACTUAL_OFFER = `CHANGE_ACTUAL_OFFER`;
export const CHANGE_ACTUAL_FILTER = `CHANGE_ACTUAL_FILTER`;
